---
# tasks file for base
- name: Install Ubuntu OS packages
  apt:
    name: "{{ ubuntu_os_packages }}"
    state: latest
    update_cache: yes
  when: ansible_os_family == 'Debian'

- name: Install Centos OS packages
  yum:
    name: "{{ centos_os_packages }}"
    state: present
    update_cache: yes
  when: ansible_os_family == 'RedHat'

- name: Install pip3 packages
  pip:
    name: "{{ pip3_packages }}"
    state: latest
    executable: pip3


- include: goss.yml
- include: users.yml
