---
# scenario:
#   test_sequence:
#     - dependency
#     - lint
#     - cleanup
#     - destroy
#     - syntax
#     - create
#     - prepare
#     - converge
#     - side_effect
#     - verify
#     - cleanup
#     - destroy
dependency:
  name: galaxy
driver:
  name: vagrant
platforms:
  - name: ubuntu2004
    box: ubuntu/focal64
  - name: centos-8
    box: centos/8
provisioner:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint .
verifier:
  name: testinfra
