---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: quay.io/paulfantom/molecule-systemd:ubuntu-18.04
    pre_build_image: true
provisioner:
  name: ansible
  inventory:
    group_vars:
      python3:
        ansible_python_interpreter: /usr/bin/python3
verifier:
  name: ansible
